### ISSUE TITLE
graphics only in compatibility mode on Lenovo ThinkPad P15s Gen 2

### ISSUE THREAD

**Issue by PeterKamm** [linuxmint/mint20.3-beta#23]
LM20.3beta cinnamon boots on Lenovo ThinkPad P15s Gen 2 (P# 20W7S0AG00, Lenovo_MT_20W7_BU_Think_FM_ThinkPad P15s Gen 2i), but only in compatibility mode, it initializes correctly the graphic driver 

I tried to boot it from a USB-stick, ended up in:
[ xxxx ] nouveau 0000:01:00.0 tmr: stalled at fffff...fffff
[ xxxx ] nouveau 0000:01:00.0 DRM: failed to idle channel 0 [DRM]

in compatibility mode it boots and initialized the graphics (tested with ventoy.net from a USB-SSD) mate & xfce (ventoy) same issue. LM20.2c (USB) and LM20.2m (ventoy) same issue.

The LMs do seem to boot, but print error messages on the text-white-on-black startup screen (no LM-logo, no graphics), and can be powered down pressing the power-button of the P15s.

**Comment by xenopeek** [comment]
Linux Mint 20.3 comes with Linux kernel 5.4. You may likely need a newer kernel for the NVIDIA Quadro T500 graphics chip in that laptop, because the chip is newer than the kernel. For this reason we have an Edge ISO, for systems that need a newer kernel to work well: https://linuxmint-user-guide.readthedocs.io/en/latest/edge.html. Currently we have a Linux Mint 20.2 Edge ISO that comes with kernel 5.11. The Edge ISO will be upgraded to Linux Mint 20.3 after the beta and will then come with kernel 5.13 I think.

**Comment by PeterKamm** [comment]
Thxalot for Your hint on the edge-iso, which I did not know before. LM20.2c-edge works on LTP P15s-g2.
I wonder, if I should install it or better wait for LM20.3. Might upgrading from LM20.2-edge to LM20.3 downgrade to an older kernel again, so I would have to change it manually?
Up to now, I did not have any issues when upgrading the LM-version, THANK YOU all LM-guys for Your efforts !!!

**Comment by WhosyVox** [comment]
Upgrading from Mint 20.2 to 20.3 won't downgrade your kernel. Unless you plan to continue in beta-testing the new release, you should stick to the .2 release.

**Comment by daedroza** [comment]
Would 20.3 Edge ISO be released immediately after we move from beta to stable release? @WhosyVox

**Comment by PeterKamm** [comment]
I installed LM20.3c-beta on P15s-g2 and it runs well. Thanx.
