### ISSUE TITLE
Make a screenshot of the 'current window' break Cinnamon

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint20.3-beta#4]
Checking the live usb I found the following bug:

Taking a screenshot using the 'Print Screen' key and from there going back to the 'Grab the current window option' and taking the screenshot caused Cinnamon to crash and go into 'Fall back mode'.

(Then when using this screenshot mode again gnome-screenshot [does not include the wallpaper](https://user-images.githubusercontent.com/68134588/145636143-7ce85680-f823-429c-afea-f41c9bd2ba38.png))

---
[logs - xsession-errors](https://github.com/linuxmint/mint20.3-beta/files/7695252/gnome-screenshot.vs.cinnamon.zip)

**Comment by clefebvre** [comment]
Let me get that straight.. you're taking a screenshot of the screenshot window?

**Comment by haggen88** [comment]
@clefebvre  No. I made a screenshot through the keyboard button and went back  [1] to the 'Grab the current window' option [2]. I took that screenshot  and Cinnamon crash.

I exemplify it through these images [of my LM 20.2]

![a](https://user-images.githubusercontent.com/68134588/145654628-46d59dd6-ac1d-4958-be60-3c6c9698efe8.png)
![b](https://user-images.githubusercontent.com/68134588/145654640-a3a51a72-c27d-4731-98e2-e262277822b4.png)

.....

... and after Cinnamon went into 'Fall back mode'  I tried to take another screenshot of the desktop with the 'Grab the current window' option and the image doesn't show the [wallpaper](https://user-images.githubusercontent.com/68134588/145636143-7ce85680-f823-429c-afea-f41c9bd2ba38.png).

**Comment by WhosyVox** [comment]
I've been unable to replicate this from within a VM.

1. Are you running a dedicated GPU? If so it would be useful to know what the model is.
1a. If it's also Nvidia, what drivers are you running?
1b. Have you installed a different kernel?

2. It seems you have several customisations running on your Mint install. Does this same bug occur from a fresh install?

Edit:
Have replicated the issue, though steps to achieve it are yet unclear.

Edit 2:
Under current Mint 20.2 the behaviour of the tool seems to be that it will simply fail to take a screenshot.
I suspect this is because this configuration window is the active window. When you hit the button the window will close, giving you no target to screenshot.

Edit 3:
The reason this was inconsistent and thus I couldn't replicate prior, is that it introduces a race condition: will the window close first, or screenshot be taken first?

Since the Mint 20.3 screenshot utility uses a newer(?) version, 3.36.0-linuxmint2 rather than 3.36.0-linuxmint1, perhaps we should check the commits between releases. Though just patching in a check for if the window we're targetting actually exists before attempting to take a screenshot sounds like a workable solution. Or just don't let you take a screenshot of that window, since it's a weird idea.

Edit 4:
Installing the previous version (3.36.0-linuxmint1) from the Ulyana repositories resolves the problem.

Edit 5:
Issue exists possibly in screenshot-utils.c.
My guess based on the error message I received would be around line 745. `screenshot` is null because the window is gone, so it's defaulting to the fallback method which is possibly crashing Cinnamon?
(Checking the stdout of gnome-screenshots at the time of the error triggered the X11 fallback message.)

**Comment by WhosyVox** [comment]
I don't have a suitable environment to compile and test the above assumptions or hypothesis. I'm not sure where the code repository is, had to track the files down from the source-code in the repos themselves.

Still, hopefully it's a bug that can be squashed sometime. And it seems like it could legitimately happen any time a window is closed between the request to take a screenshot and the event of taking said screenshot.

**Comment by haggen88** [comment]
@WhosyVox @clefebvre 

>Are you running a dedicated GPU? If so it would be useful to know what the model is.

I don't have a dedicated graphics card  [intel hd 4000]
    
>1a. If it's also Nvidia, what drivers are you running?

nope

- Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: **Dell driver: i915** v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 21.0.3 
           compat-v: 3.0 direct render: Yes 

>1b. Have you installed a different kernel?

I have not changed the kernel

>It seems you have several customisations running on your Mint install. Does this same bug occur from a fresh install?

The photos are from Mint 20.2, to explain how to reproduce the bug . The bug occurs in LM 20.3 beta Cinnamon [Live USB].

> Have replicated the issue, though steps to achieve it are yet unclear.

Steps to reproduce:

1) occupy the 'print screen key' to take a screenshot
2) once the screenshot window is open [which displays the options to change the file name and save location]   go back to the screenshot options.
3) select the option 'Grab the current window'
4) take the screenshot 


https://user-images.githubusercontent.com/68134588/145696726-8888cf07-a198-46f6-b03b-3d423bbf440e.mp4

---
mint@mint:~$ gnome-screenshot
** Message: 21:38:31.717: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(gnome-screenshot:2241): Gdk-ERROR **: 21:38:31.730: The program 'gnome-screenshot' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
(Details: serial 3543 error_code 3 request_code 15 (core protocol) minor_code 0)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the GDK_SYNCHRONIZE environment
variable to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

**Comment by hammy275** [comment]
Interestingly enough, I get the exact same console output when performing the above steps on Linux Mint 20.2, however Cinnamon doesn't warn about crashing and needing to enter fallback mode.

**Comment by haggen88** [comment]
Console output [LM 20.2]:

---
h2gn@h2gn:~$ gnome-screenshot

(gnome-screenshot:5911): Gdk-ERROR **: 19:53:26.303: The program 'gnome-screenshot' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3780 error_code 3 request_code 15 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
«trap» para punto de parada/seguimiento (`core' generado)

**Comment by google-goldfish** [comment]
Yup, indeed a issue. On 20.2, there is no crash however the Take Screenshot function doesn't work when going through above steps from video.

**Comment by clefebvre** [comment]
Fixed in gnome-screenshot 3.36.0-linuxmint3.
