### ISSUE TITLE
[feature request]  Cinnamon Mint-Y Slim Window Borders

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint20.3-beta#8]
I know this is a long shot at this stage.  Just requesting if there could be an option for Mint-Y slimmer top window title/borders.  Mint-Y Slim.
1.)  Slightly smaller buttons.
2.)  A 4 px radius instead of a 8 px radius.
3.)  Not as tall as the existing Mint-Y option.

**Comment by WhosyVox** [comment]
It seems like this theme change has been implemented due to the forced theming of Gnome apps using Adwaita. The curvature and size match up almost perfectly.

Although personally I'd rather have most of my windows still square and put up with adwaita rounded nonsense on a few apps, than have everything so horribly rounded. That's why I'm keeping the older Mint-Y theme in my system post-upgrade.

**Comment by LinuxOnTheDesktop** [comment]
> That's why I'm keeping the older Mint-Y theme in my system post-upgrade.

Cf. [my comment elsewhere on the beta bug-tracker](https://github.com/linuxmint/mint20.3-beta/issues/6#issuecomment-991395572).

**Comment by WhosyVox** [comment]
> Cf. [my comment elsewhere on the beta bug-tracker](https://github.com/linuxmint/mint20.3-beta/issues/6#issuecomment-991395572).

Or as per my reddit post before that, where I also happened to call it Mint-Z.
https://www.reddit.com/r/linuxmint/comments/rd6mep/comment/hnzfjg3/?utm_source=share&utm_medium=web2x&context=3

It seems like there's definite value in keeping the older theme version in the system, even if it's not the default choice on a new install or even post-upgrade.

But this ought to be its own request rather than piggybacking off other issues.

**Comment by Harry-W-Haines-III** [comment]
Yes, I see the problem now with Calculator, Calendar, Cheese, Clocks, Font, Hypnotix, Warpinator, Weather.  Those are the exceptions, other major applications look fine under the old Mint-Y theme I copied over from LM 20.2 as Mint-Z such as Evolution, LibreOffice, etc.

So at this point, are we always going to be tied to what Ubuntu does with its GUI?  I use Mint-X all the time (so this is not an issue for me) but for the sake of testing also checked Mint-Y and was just a put off by the mobile app look of it.

IMHO, for Cinnamon to continue to succeed, it needs to be it's own stand alone interface.   Or else there is Plasma.

**Comment by WhosyVox** [comment]
In theory I think it's possible to fork Adwaita and re-theme it, but it doesn't fix the main issue that Adwaita-based apps no longer follow the user-defined theme. At best we can put in a lot of effort to switch it all over to Mint-Y, but then if you decide to use another theme then it still fails to match.

**Comment by Harry-W-Haines-III** [comment]
It is possible to minimize this issue with all the applications.  Take a look at https://www.gnome-look.org/p/1271140
The first theme, Blue Sky Light.

**Comment by haggen88** [comment]
Regarding the design ... in my opinion the window close button is too close to the edge of the window.
Comparing it with the one in gnome 40:

![lm 20 3 beta](https://user-images.githubusercontent.com/68134588/145720554-46b1e038-b57a-4d24-b4c6-b62b6bb88e54.png)
![button g40](https://user-images.githubusercontent.com/68134588/145720564-475df1ad-74b0-4eee-aa4a-e2a6718e46a0.png)

**Comment by enigma131** [comment]
I agree with query ,  I'm on laptop with 15 inch screen

**Comment by Secret-chest** [comment]
> In theory I think it's possible to fork Adwaita and re-theme it, but it doesn't fix the main issue that Adwaita-based apps no longer follow the user-defined theme. At best we can put in a lot of effort to switch it all over to Mint-Y, but then if you decide to use another theme then it still fails to match.

Fork it and make a program that sets it to the current theme.

**Comment by OdinVex** [comment]
> Yes, I see the problem now with Calculator, Calendar, Cheese, Clocks, Font, Hypnotix, Warpinator, Weather. Those are the exceptions, other major applications look fine under the old Mint-Y theme I copied over from LM 20.2 as Mint-Z such as Evolution, LibreOffice, etc.
> 
> So at this point, are we always going to be tied to what Ubuntu does with its GUI? I use Mint-X all the time (so this is not an issue for me) but for the sake of testing also checked Mint-Y and was just a put off by the mobile app look of it.
> 
> IMHO, for Cinnamon to continue to succeed, it needs to be it's own stand alone interface. Or else there is Plasma.

It's more a problem not of Ubuntu but rather with Gnome. Gnome has demostrated their determination to “redefine” the desktop experience. In my opinion, I'm eventually going to have to leave anything Gnome/Gtk because of it and go KDE/Qt. I'm putting it mildly.

Edit: Granted, Gnome might look alright on small devices, but in my opinion they've completely destroyed the desktop experience.

**Comment by Secret-chest** [comment]
> > In theory I think it's possible to fork Adwaita and re-theme it, but it doesn't fix the main issue that Adwaita-based apps no longer follow the user-defined theme. At best we can put in a lot of effort to switch it all over to Mint-Y, but then if you decide to use another theme then it still fails to match.
> 
> Fork it and make a program that sets it to the current theme.

Read.

**Comment by clefebvre** [comment]
Assuming we did a slim version, it wouldn't be consistent with CSD windows (which use the GTK theme).

**Comment by clefebvre** [comment]
Legacy provides this already and in a compatible way with its own Gtk theme.
